# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-05 20:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('slytherin', '0004_auto_20170305_1717'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='title_after',
        ),
        migrations.RemoveField(
            model_name='post',
            name='title_before',
        ),
    ]
