# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-06 11:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slytherin', '0010_auto_20170306_1016'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='slug',
            field=models.SlugField(default='test', editable=False, max_length=1024, unique=True),
            preserve_default=False,
        ),
    ]
