# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-06 12:33
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slytherin', '0011_auto_20170306_1110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='alt',
            field=models.CharField(blank=True, editable=False, max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='body',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
