# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-06 13:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slytherin', '0017_auto_20170306_1310'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='priority',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
