# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-06 14:53
from __future__ import unicode_literals

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slytherin', '0018_section_priority'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='body',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
        migrations.AlterField(
            model_name='section',
            name='priority',
            field=models.SmallIntegerField(default=0),
        ),
    ]
