# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-06 15:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('slytherin', '0019_auto_20170306_1453'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Post',
            new_name='Publication',
        ),
    ]
