# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-06 15:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('slytherin', '0021_auto_20170306_1540'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publication',
            name='thumbnail_image',
        ),
    ]
