# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-05 22:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='verbose_title',
            field=models.CharField(default='Mobile and Desktop Apps', max_length=1024),
            preserve_default=False,
        ),
    ]
