# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-05 00:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='slug',
            field=models.CharField(max_length=32, unique=True),
        ),
    ]
