# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-05 21:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20170305_2043'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='release_date',
        ),
    ]
