# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-05 21:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_remove_post_release_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='verbose_title',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
    ]
