# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-06 12:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_auto_20170306_1233'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='compiled_body',
        ),
    ]
