# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-06 13:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0015_auto_20170306_1245'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='side',
        ),
    ]
