# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-06 15:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0020_auto_20170306_1532'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publication',
            name='publication_date',
        ),
        migrations.AddField(
            model_name='publication',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='publication',
            name='modified_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
