# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-05 16:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nt_site', '0002_remove_post_preview'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='published',
            new_name='draft',
        ),
    ]
