# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-06 12:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nt_site', '0013_remove_post_compiled_body'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='lead',
        ),
    ]
