# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-06 15:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nt_site', '0022_remove_publication_thumbnail_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='publication',
            old_name='body',
            new_name='content',
        ),
    ]
