# Generated by Django 2.0.3 on 2018-09-16 14:09

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.ImageField(upload_to='images')),
                ('retina', models.BooleanField(default=False)),
                ('slug', models.SlugField(editable=False, max_length=1024, unique=True)),
                ('alt', models.CharField(blank=True, editable=False, max_length=1024, null=True)),
                ('caption', models.CharField(blank=True, max_length=1024, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256)),
                ('slug', models.SlugField(editable=False, max_length=256, unique=True)),
                ('content', ckeditor_uploader.fields.RichTextUploadingField()),
                ('hidden', models.BooleanField(db_index=True, default=False)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128, unique=True)),
                ('slug', models.SlugField(editable=False, max_length=128, unique=True)),
                ('priority', models.SmallIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blog_title', models.CharField(max_length=1024)),
                ('blog_copyright', models.CharField(max_length=1024)),
                ('author_email', models.EmailField(max_length=254)),
                ('counter_yandex_metrika', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'settings',
            },
        ),
        migrations.AddField(
            model_name='publication',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='posts', to='public.Section'),
        ),
        migrations.AddField(
            model_name='image',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='public.Publication'),
        ),
        migrations.AlterUniqueTogether(
            name='image',
            unique_together={('post', 'slug')},
        ),
        migrations.AlterIndexTogether(
            name='image',
            index_together={('post', 'slug')},
        ),
    ]
