# Generated by Django 2.2.2 on 2019-06-19 10:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='settings',
            old_name='counter_yandex_metrika',
            new_name='footer',
        ),
        migrations.RemoveField(
            model_name='settings',
            name='author_email',
        ),
        migrations.RemoveField(
            model_name='settings',
            name='blog_copyright',
        ),
    ]
