# Generated by Django 2.2.2 on 2019-06-16 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='internal_title',
            field=models.CharField(default='', max_length=256),
            preserve_default=False,
        ),
    ]
