# Generated by Django 2.2.2 on 2019-06-16 18:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='side',
            new_name='sidebar',
        ),
    ]
